name = "tlt-stops"
main = "build/worker/shim.mjs"
compatibility_date = "2025-11-04"

[build]
command = "cargo install worker-build && worker-build --release"
dcommand = "worker-build --dev"
rcommand = "worker-build --release"

[observability]
enabled = true

[placement]
mode = "smart"
